spring:
  servlet:
    multipart:
      #      取消上传文件大小限制
      max-file-size: -1
      max-request-size: -1

  redis:
    database: 0
    host: 10.16.196.50
    #    host: 10.4.252.102
    password: 210093
    port: 6379
    timeout: 0
    deviceChannel: device

  application:
    name: translationTool
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/translationtool?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #
    url: jdbc:mysql://10.16.196.50:3306/translationtool?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true

    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 18001


#logging:
 # config: ./logback-spring.xml

translate:
  #  百度翻译api信息
  baidu:
    url: http://api.fanyi.baidu.com/api/trans/vip/translate
    appid: 20230705001734655
    securityKey: Msyn6CIJy97uY1MXLW0c
  #  DeepL翻译api信息
  deepl:
    url: https://api.deepl-pro.com
    key: b253ec17-0877-4a1f-81cb-72c5f824b32c:dp
  #  有道翻译api信息
  youdao:
    url: https://openapi.youdao.com/api
    appKey: aCwCTdgEH1lVY1DEfTXjnIV8dJbgD8sZ
    appKeyID: 12539761968f9072


logging.level.com.shr.translationtoolservice.dao: debug
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.shr.translationtoolservice.entity
  ##configuration:
   # cache-enable: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #call-setters-on-nulls: true

logging:
  config: classpath:logback-spring.xml
  level:
    com.shr.translationtoolservice.dao: debug

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.shr.translationtoolservice.entity
  #configuration:
   # cache-enable: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #call-setters-on-nulls: true
#是否开启swagger
swagger:
  enabled: true

ldap:
  ldapURL: ldap://10.16.2.171:389
  accountSuffix: "@sp5000.com"
  base: "DC=sp5000,DC=com"
  user: "Administrator"
  password: "Admin@1234"

log:
  level: debug

I18server:
  #url: http://10.16.193.26:18099/
  #linx
  url: http://10.16.193.185:18099/
  #url: http://10.16.193.63:18099/
ConfigFile:
  zzUrl: "src/main/resources/config/装置词条翻译模板_zz.xlsx"
  commonUrl: "src/main/resources/config/通用词条翻译模板_common.xlsx"
  #linx
  #url: "./config/import.xls"


